#!/usr/bin/env zsh

string=$1
attach=$2
string_copy=$string
matches=()

# func to determine the correct extension
function dirntype() {
	local EXT=$1

	case "$EXT" in
		photo) echo -n $2 ;;
		audio) echo -n "m4a" ;;
		pdfattachment) echo -n $2 ;;
		*)
			echo -n 'NONE'
		;;
	esac
}

# First check if the string contains any dayone links
if [[ $string_copy =~ (dayone-moment:/) ]]; then

	# only looks for links to photos, audio, and PDFs
	pattern="(dayone-moment:/(/|audio/|pdfAttachment/)[a-zA-Z0-9]{32})"
	while [[ $string_copy =~ $pattern ]]; do
	    # Add the matched text to the "matches" array
	    matches+=("${match[1]}")

			# rm the instance from the string copy
	    string_copy=${string_copy#*$match[1]}
	done

	for match in $matches; do
		# rm the dayone dir
		# there was an \r causing trouble, window BS
		local ID=`echo -n "$match" | sed -E 's#dayone-moment:/(/|audio/|pdfAttachment/)*##g'`

		local LINE=`bat $attach | grep $ID | tr -d "\n" | tr -d "\r"` 
		local elements=("${(s/,/)LINE}")
		local MD5=$elements[1]
		local TYPE=`echo $elements[3] | tr '[:upper:]' '[:lower:]'`
		local FLTYPE=`echo $elements[4]`
		local EXT=`dirntype $TYPE $FLTYPE`
		local FL=../$TYPE\/$MD5.$EXT

		# now replace it in the main string
		string=`echo $string | sed -E "s#$match#$FL#g"`
		echo $FL
	done
fi

echo $string
